# Setup
title:               «Я&nbsp;—&nbsp;профессионал»
tagline:             'beta-testing'
description:         '«Я&nbsp;—&nbsp;профессионал» BETA'
url:                 https://dgorpinchuk.github.io
baseurl:             '/ya-profi-beta'
paginate:            5
permalink:           pretty

# About/contact
author:
name:              Dmitry Gorpinchuk
url:               https://twitter.com/dimon92
email:             dgorpinchuk@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
